- hosts: all
  remote_user: root
  vars:
      db_name: kanboard 
      domain_name: "{{ domain_name_var }}"
      admin_user: "{{ admin_user_var }}"
      admin_pwd:  "{{ admin_pwd_var }}"
      kan_version: 1.2.5
      
  tasks: 
    - name: Install required debs
      apt: 
        name: "{{ item }}"
        state: present
      with_items: 
        - php7.0-fpm
        - php7.0-mbstring
        - php7.0-mcrypt
        - php7.0-sqlite3
        - php7.0-opcache
        - php7.0-json
        - php7.0-mysql
        - php7.0-pgsql
        - php7.0-xml
        - php7.0-cli
        - php7.0-ldap
        - php7.0-gd
        - apache2
        - libapache2-mod-php7.0

    - name: Download Kanboard
      get_url:
          url: "https://github.com/kanboard/kanboard/archive/v{{ kan_version }}.tar.gz"
          dest: /tmp/kanboard.tgz

    - name: Extract Kanboard tar ball
      unarchive:
          remote_src: yes
          src:  /tmp/kanboard.tgz
          dest: /var/www
          owner: www-data
          group: www-data

    - name: Copy app config file
      copy:
          src: config.php
          dest: /var/www/kanboard/config.php

    - name: Create DataBase User
      mysql_user:
          name: "{{ admin_user }}"
          password: "{{ admin_pwd }}"
          priv: "*.*:ALL"
          state: present

    - name: Create DataBase
      mysql_db:
          name: "{{ db_name }}"
          encoding: utf8
          state: present

    - name: Copy apache config file
      copy:
          src: kanboard_site.conf
          dest: /etc/apache2/sites-available/kanboard

    - name: remove default site file
      file:
          name: /etc/apache2/sites-available/000-default.conf
          state: absent

    - name: restart apache2 server
      service:
          name: apache2
          state: restarted
